backend:
  image: "shreybatra/sample-backend"
  port: 8000
  env:
    REDIS_URI: "redis://redis-svc:6379"

frontend:
  image: "shreybatra/sample-frontend"
  port: 5173
  env:
    BACKEND_URL: "http://backend-svc:8000"

redis:
  image: "redis"
  port: 6379